FROM python:3.11-slim

# Injected by build.sh: "<semver>-<git-sha>", e.g. "1.2.3-a4f9e1b"
# Falls back to "dev" when building without the script (plain `docker build .`).
ARG BUILD_VERSION=dev

# Keeps Python from buffering stdout/stderr (logs appear immediately in Cloud Run / Docker)
# and prevents .pyc files being written into the image layer.
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    APP_VERSION=${BUILD_VERSION}

# Stamp the image so `docker inspect` and registries show the version.
LABEL version="${BUILD_VERSION}"

WORKDIR /app

# Install dependencies first so this layer is cached on re-builds
# unless requirements.txt changes.
# requirements-serve.txt contains ONLY production/serving deps (no torch, no CUDA).
# Generated by build.sh via: uv export --no-dev -o requirements-serve.txt
# Never use the full requirements.txt here — it pulls in ~2.5 GB of CUDA wheels.
COPY requirements-serve.txt .
RUN pip install --no-cache-dir -r requirements-serve.txt

# Copy model artifacts and application code.
# __init__.py files are included via app/ so the package is importable.
COPY onnx_model/ ./onnx_model/
COPY models/     ./models/
COPY app/        ./app/

EXPOSE 8000

# Use exec form so gunicorn is PID 1 and receives SIGTERM directly from the
# container runtime (graceful shutdown).  `sh -c` + `exec` is required to
# keep shell-variable expansion for WEB_CONCURRENCY while still replacing
# the shell process with gunicorn.
CMD ["sh", "-c", "exec gunicorn app.main:app \
    -k uvicorn.workers.UvicornWorker \
    --workers ${WEB_CONCURRENCY:-4} \
    --bind 0.0.0.0:8000 \
    --timeout 30 \
    --access-logfile -"]